update pre/post commit hooks
Because we're sending input from the git diff-index to the shell,
we set IFS to newline so it splits variables from input on newlines, rather
than spaces.

diff --git a/etc/git/hooks/pre-commit b/etc/git/hooks/pre-commit
--- a/etc/git/hooks/pre-commit
+++ b/etc/git/hooks/pre-commit
@@ -23,91 +23,111 @@ fi
 function pre_commit_php_lint() {
 echo "==> pre-commit: syntax check..."
 # get a list of staged files
+
+# set IFS (internal field separator) to the newline character so that we
+# correctly split each line in the output `git diff-index` on newline characters.
+#
+# the `for` is using `read` on our input, and so we need to set ifs to do
+# variable splitting correctly.
+IFS='
+'
+
 for line in $(git diff-index --cached --full-index $AGAINST)
 do
-	# split needed values
-	# see 'Raw output format' at http://git-scm.com//docs/git-diff-index for details
-	sha=$(echo $line | cut -d' ' -f4)
-	temp=$(echo $line | cut -d' ' -f5)
-	status=$(echo $temp | cut -d'	' -f1)
-	filename=$(echo $temp | cut -d'	' -f2)
+  echo $line
+  # split needed values
+  # see 'Raw output format' at http://git-scm.com//docs/git-diff-index for details
+  sha=$(echo $line | cut -d' ' -f4)
+  temp=$(echo $line | cut -d' ' -f5)
+  status=$(echo $temp | cut -d'	' -f1)
+  filename=$(echo $temp | cut -d'	' -f2)
 
-	# file extension
-	ext=$(echo $filename | sed 's/^.*\.//')
+  # file extension
+  ext=$(echo $filename | sed 's/^.*\.//')
 
-	# only check files with php extension
-	if [ $ext != "php" ]
-	then
-		continue
-	fi
+  # only check files with php extension
+  if [ $ext != "php" ]
+  then
+    continue
+  fi
 
-	# do not check deleted files
-	if [ $status = "D" ]
-	then
-		continue
-	fi
+  # do not check deleted files
+  if [ $status = "D" ]
+  then
+    continue
+  fi
 
-	# check the staged file content for syntax errors
-	# using php -l (lint)
-	result=$(git cat-file -p $sha | php -n -l -ddisplay_errors\=1 -derror_reporting\=E_ALL -dlog_errrors\=0 2>&1)
-	if [ $? -ne 0 ]
-	then
-		# Swap back in correct filenames
-		errors=$(echo "$errors"; echo "$result" | grep ':' | sed -e "s@in - on@in $filename on@g")
-	fi
+  # check the staged file content for syntax errors
+  # using php -l (lint)
+  echo "==> check $sha : $filename ..."
+  result=$(git cat-file -p $sha | php -n -l -ddisplay_errors\=1 -derror_reporting\=E_ALL -dlog_errrors\=0 2>&1)
+  if [ $? -ne 0 ]
+  then
+    # Swap back in correct filenames
+    errors=$(echo "$errors"; echo "$result" | grep ':' | sed -e "s@in - on@in $filename on@g")
+  fi
 done
 
 if [ -n "$errors" ]
 then
-	echo "==> pre-commit: syntax check failed. "
-	echo "$errors"
-	errors=""
-	exit 1
+  echo "==> pre-commit: syntax check failed. "
+  echo "$errors"
+  errors=""
+  exit 1
 fi
+
+unset IFS
 }
 
 function pre_commit_php_debugging() {
-echo "==> pre-commit: syntax check..."
+echo "==> pre-commit: debugging check..."
+
+IFS='
+'
+
 # get a list of staged files
 for line in $(git diff-index --cached --full-index $AGAINST)
 do
-	# split needed values
-	# see 'Raw output format' at http://git-scm.com//docs/git-diff-index for details
-	sha=$(echo $line | cut -d' ' -f4)
-	temp=$(echo $line | cut -d' ' -f5)
-	status=$(echo $temp | cut -d'	' -f1)
-	filename=$(echo $temp | cut -d'	' -f2)
+  # split needed values
+  # see 'Raw output format' at http://git-scm.com//docs/git-diff-index for details
+  sha=$(echo $line | cut -d' ' -f4)
+  temp=$(echo $line | cut -d' ' -f5)
+  status=$(echo $temp | cut -d'	' -f1)
+  filename=$(echo $temp | cut -d'	' -f2)
 
-	# file extension
-	ext=$(echo $filename | sed 's/^.*\.//')
+  # file extension
+  ext=$(echo $filename | sed 's/^.*\.//')
 
-	# only check files with php extension
-	if [ $ext != "php" ]
-	then
-		continue
-	fi
+  # only check files with php extension
+  if [ $ext != "php" ]
+  then
+    continue
+  fi
 
-	# do not check deleted files
-	if [ $status = "D" ]
-	then
-		continue
-	fi
+  # do not check deleted files
+  if [ $status = "D" ]
+  then
+    continue
+  fi
 
-	# check the staged file content for calls to debugging functions
-	result=$(git cat-file -p $sha | grep -n "\(var_dump\|print_r\|debug_print_backtrace\|error_log\)")
-	if [ $? -ne 1 ]
-	then
-		errors=$(echo "$errors"; echo "FILE: $filename\n$result")
-	fi
+  echo "==> check $sha : $filename ..."
+  # check the staged file content for calls to debugging functions
+  result=$(git cat-file -p $sha | grep -n "\(var_dump\|print_r\|debug_print_backtrace\|error_log\)")
+  if [ $? -ne 1 ]
+  then
+    errors=$(echo "$errors"; echo "FILE: $filename\n$result")
+  fi
 done
 
 if [ -n "$errors" ]
 then
-	echo "==> pre-commit: debugging check failed."
-	echo "$errors"
-	errors=""
-	exit 1
+  echo "==> pre-commit: debugging check failed."
+  echo "$errors"
+  errors=""
+  exit 1
 fi
+
+unset IFS
 }
 
 pre_commit_php_lint
